name: La Paz Cloud pipeline example with Github Actions

on:
- push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Use NodeJS
      uses: actions/setup-node@v1

    - run: npm install
      env:
        CI: true

    - run: npm test
